### ISSUE TITLE
Add support for stopping work at beginning of the deploy

### ISSUE THREAD

**Issue by technicalpickles** [railsmachine/moonshine_sidekiq#1]
Sidekiq has built in support for stopping work at the start of the deploy, so that would be nice to have as well. It'd probably be a cap task more or less copypastad from sidekiq/capistrano.

**Comment by kplawver** [comment]
If I understand correctly, sidekiq already quiets itself at the beginning of deploys assuming you're requiring 'sidekiq/capistrano', so I don't see why we'd add it to the plugin.  Re-open if you disagree.
